import type { Skill } from "./types"

/**
 * The shared skill vocabulary. Careers reference these by id, which is what
 * makes cross-industry transfer computable: if two careers in different
 * industries share skill ids, the tool can say so honestly instead of guessing.
 */
export const SKILLS: Skill[] = [
  // --- Physical & hands-on ------------------------------------------------
  {
    id: "manual-labor",
    name: "Manual labor",
    category: "physical",
    description: "Sustained physical work: lifting, carrying, digging, and being on your feet.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["hand-tools", "site-prep"],
  },
  {
    id: "hand-tools",
    name: "Hand & power tools",
    category: "physical",
    description: "Safe, confident use of drills, saws, grinders, and measuring tools.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["manual-labor", "carpentry", "measuring"],
  },
  {
    id: "measuring",
    name: "Measuring & layout",
    category: "technical",
    description: "Reading a tape, marking accurate lines, and working to tolerance.",
    industries: ["solar", "landscaping", "renovation"],
    relatedSkills: ["blueprint-reading", "math-fundamentals"],
  },
  {
    id: "ladder-roof",
    name: "Ladder & roof work",
    category: "physical",
    description: "Working safely at height with fall protection.",
    industries: ["solar", "renovation"],
    relatedSkills: ["safety-osha", "manual-labor"],
  },
  {
    id: "site-prep",
    name: "Site preparation",
    category: "physical",
    description: "Clearing, grading, and staging a work area before the real job starts.",
    industries: ["landscaping", "renovation", "agriculture"],
    relatedSkills: ["manual-labor", "heavy-equipment"],
  },
  {
    id: "material-handling",
    name: "Material handling",
    category: "physical",
    description: "Staging, protecting, and moving materials without damage or waste.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["manual-labor", "inventory"],
  },

  // --- Technical ----------------------------------------------------------
  {
    id: "electrical-basics",
    name: "Electrical fundamentals",
    category: "technical",
    description: "Voltage, current, circuits, and how to work around them safely.",
    industries: ["solar", "renovation", "agriculture"],
    relatedSkills: ["wiring", "troubleshooting", "safety-osha"],
  },
  {
    id: "wiring",
    name: "Wiring & terminations",
    category: "technical",
    description: "Pulling, landing, and terminating conductors to code.",
    industries: ["solar", "renovation"],
    relatedSkills: ["electrical-basics", "conduit", "code-knowledge"],
  },
  {
    id: "conduit",
    name: "Conduit bending & routing",
    category: "technical",
    description: "Planning and bending raceway runs that are clean and compliant.",
    industries: ["solar", "renovation"],
    relatedSkills: ["wiring", "measuring"],
  },
  {
    id: "pv-systems",
    name: "PV system knowledge",
    category: "technical",
    description: "How arrays, inverters, and stringing decisions fit together.",
    industries: ["solar"],
    relatedSkills: ["electrical-basics", "battery-storage", "system-design"],
  },
  {
    id: "battery-storage",
    name: "Battery & storage systems",
    category: "technical",
    description: "Sizing, installing, and commissioning energy storage safely.",
    industries: ["solar"],
    relatedSkills: ["pv-systems", "electrical-basics"],
  },
  {
    id: "system-design",
    name: "System design & sizing",
    category: "technical",
    description: "Turning a site and a load profile into a specified system.",
    industries: ["solar", "landscaping", "agriculture"],
    relatedSkills: ["cad-software", "math-fundamentals", "pv-systems"],
  },
  {
    id: "blueprint-reading",
    name: "Blueprint & plan reading",
    category: "technical",
    description: "Interpreting drawings, schedules, and details before you build.",
    industries: ["solar", "landscaping", "renovation"],
    relatedSkills: ["measuring", "cad-software"],
  },
  {
    id: "carpentry",
    name: "Carpentry",
    category: "technical",
    description: "Framing, cutting, and joining wood to structural tolerance.",
    industries: ["renovation", "agriculture"],
    relatedSkills: ["hand-tools", "blueprint-reading", "finish-work"],
  },
  {
    id: "finish-work",
    name: "Finish & trim work",
    category: "technical",
    description: "The visible last 10%: trim, doors, cabinets, and clean lines.",
    industries: ["renovation"],
    relatedSkills: ["carpentry", "painting", "attention-detail"],
  },
  {
    id: "drywall",
    name: "Drywall & plaster",
    category: "technical",
    description: "Hanging, taping, and finishing wall surfaces.",
    industries: ["renovation"],
    relatedSkills: ["finish-work", "painting"],
  },
  {
    id: "painting",
    name: "Painting & coatings",
    category: "technical",
    description: "Surface prep, spraying, and coatings that actually last.",
    industries: ["renovation"],
    relatedSkills: ["drywall", "attention-detail"],
  },
  {
    id: "plumbing",
    name: "Plumbing",
    category: "technical",
    description: "Supply, waste, and venting systems, plus fixture installation.",
    industries: ["renovation", "agriculture"],
    relatedSkills: ["pipefitting", "code-knowledge", "troubleshooting"],
  },
  {
    id: "pipefitting",
    name: "Pipefitting & fusion",
    category: "technical",
    description: "Cutting, joining, and pressure-testing pipe runs.",
    industries: ["renovation", "landscaping", "agriculture"],
    relatedSkills: ["plumbing", "irrigation-systems"],
  },
  {
    id: "hvac-systems",
    name: "HVAC systems",
    category: "technical",
    description: "Heating, cooling, ventilation, and heat-pump fundamentals.",
    industries: ["renovation"],
    relatedSkills: ["refrigeration", "electrical-basics", "troubleshooting"],
  },
  {
    id: "refrigeration",
    name: "Refrigeration cycles",
    category: "technical",
    description: "Charging, recovery, and diagnosing refrigerant systems.",
    industries: ["renovation", "agriculture"],
    relatedSkills: ["hvac-systems", "troubleshooting"],
  },
  {
    id: "welding",
    name: "Welding & fabrication",
    category: "mechanical",
    description: "Joining and repairing metal for structures and equipment.",
    industries: ["renovation", "agriculture", "solar"],
    relatedSkills: ["hand-tools", "equipment-repair"],
  },
  {
    id: "masonry",
    name: "Masonry & concrete",
    category: "technical",
    description: "Forming, pouring, and laying block, brick, and stone.",
    industries: ["landscaping", "renovation"],
    relatedSkills: ["hardscape-install", "measuring"],
  },
  {
    id: "hardscape-install",
    name: "Hardscape installation",
    category: "technical",
    description: "Patios, walls, and walkways built on base that will not settle.",
    industries: ["landscaping"],
    relatedSkills: ["masonry", "site-prep", "measuring"],
  },
  {
    id: "roofing",
    name: "Roofing",
    category: "technical",
    description: "Flashing, underlayment, and penetrations that stay watertight.",
    industries: ["renovation", "solar"],
    relatedSkills: ["ladder-roof", "waterproofing"],
  },
  {
    id: "waterproofing",
    name: "Waterproofing & sealing",
    category: "technical",
    description: "Keeping water out of buildings and assemblies.",
    industries: ["renovation", "solar"],
    relatedSkills: ["roofing", "attention-detail"],
  },
  {
    id: "insulation",
    name: "Insulation & efficiency",
    category: "technical",
    description: "Air sealing and insulating to cut energy loss.",
    industries: ["renovation"],
    relatedSkills: ["energy-auditing", "hvac-systems"],
  },
  {
    id: "energy-auditing",
    name: "Energy auditing",
    category: "technical",
    description: "Measuring where a building wastes energy and what to fix first.",
    industries: ["renovation", "solar"],
    relatedSkills: ["insulation", "data-analysis"],
  },

  // --- Mechanical ---------------------------------------------------------
  {
    id: "heavy-equipment",
    name: "Heavy equipment operation",
    category: "mechanical",
    description: "Running skid steers, loaders, excavators, and tractors safely.",
    industries: ["landscaping", "renovation", "agriculture"],
    relatedSkills: ["site-prep", "equipment-maintenance"],
  },
  {
    id: "equipment-maintenance",
    name: "Equipment maintenance",
    category: "mechanical",
    description: "Servicing machines so they do not fail mid-season.",
    industries: ["landscaping", "agriculture", "solar"],
    relatedSkills: ["equipment-repair", "small-engine"],
  },
  {
    id: "equipment-repair",
    name: "Mechanical repair",
    category: "mechanical",
    description: "Diagnosing and fixing hydraulic, drivetrain, and engine faults.",
    industries: ["agriculture", "landscaping", "renovation"],
    relatedSkills: ["equipment-maintenance", "welding", "troubleshooting"],
  },
  {
    id: "small-engine",
    name: "Small engine repair",
    category: "mechanical",
    description: "Keeping mowers, trimmers, and pumps running.",
    industries: ["landscaping", "agriculture"],
    relatedSkills: ["equipment-maintenance"],
  },
  {
    id: "troubleshooting",
    name: "Troubleshooting",
    category: "technical",
    description: "Working a problem down to its cause instead of guessing.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["electrical-basics", "equipment-repair"],
  },

  // --- Irrigation & water -------------------------------------------------
  {
    id: "irrigation-systems",
    name: "Irrigation systems",
    category: "technical",
    description: "Designing and installing drip, spray, and pivot systems.",
    industries: ["landscaping", "agriculture"],
    relatedSkills: ["pipefitting", "water-management", "irrigation-controls"],
  },
  {
    id: "irrigation-controls",
    name: "Irrigation controllers",
    category: "digital",
    description: "Programming timers, sensors, and smart controllers.",
    industries: ["landscaping", "agriculture"],
    relatedSkills: ["irrigation-systems", "sensors-iot"],
  },
  {
    id: "water-management",
    name: "Water management",
    category: "environmental",
    description: "Scheduling and conserving water against real crop or plant need.",
    industries: ["landscaping", "agriculture"],
    relatedSkills: ["irrigation-systems", "soil-science"],
  },
  {
    id: "drainage",
    name: "Drainage & grading",
    category: "technical",
    description: "Moving water away from structures and root zones.",
    industries: ["landscaping", "renovation", "agriculture"],
    relatedSkills: ["site-prep", "water-management"],
  },

  // --- Growing & land -----------------------------------------------------
  {
    id: "plant-identification",
    name: "Plant identification",
    category: "environmental",
    description: "Knowing species, habits, and what will survive where.",
    industries: ["landscaping", "agriculture"],
    relatedSkills: ["horticulture", "pest-management"],
  },
  {
    id: "horticulture",
    name: "Horticulture",
    category: "environmental",
    description: "Growing and maintaining healthy plants through the season.",
    industries: ["landscaping", "agriculture"],
    relatedSkills: ["plant-identification", "soil-science", "pruning"],
  },
  {
    id: "pruning",
    name: "Pruning & trimming",
    category: "physical",
    description: "Cutting for plant health, shape, and safety.",
    industries: ["landscaping", "agriculture"],
    relatedSkills: ["horticulture", "tree-climbing"],
  },
  {
    id: "tree-climbing",
    name: "Tree climbing & rigging",
    category: "physical",
    description: "Rope work and controlled removals in the canopy.",
    industries: ["landscaping"],
    relatedSkills: ["pruning", "safety-osha"],
  },
  {
    id: "soil-science",
    name: "Soil science",
    category: "environmental",
    description: "Reading soil structure, pH, and fertility, and improving it.",
    industries: ["landscaping", "agriculture"],
    relatedSkills: ["horticulture", "crop-management"],
  },
  {
    id: "crop-management",
    name: "Crop management",
    category: "environmental",
    description: "Planning rotations, planting, and harvest windows.",
    industries: ["agriculture"],
    relatedSkills: ["soil-science", "pest-management", "harvesting"],
  },
  {
    id: "pest-management",
    name: "Pest & disease management",
    category: "environmental",
    description: "Identifying pressure early and treating it proportionately.",
    industries: ["landscaping", "agriculture"],
    relatedSkills: ["plant-identification", "chemical-application"],
  },
  {
    id: "chemical-application",
    name: "Chemical application",
    category: "safety",
    description: "Mixing and applying products legally and safely.",
    industries: ["landscaping", "agriculture"],
    relatedSkills: ["pest-management", "safety-osha"],
  },
  {
    id: "harvesting",
    name: "Harvesting & post-harvest",
    category: "physical",
    description: "Timing, handling, and storing a crop without losing quality.",
    industries: ["agriculture"],
    relatedSkills: ["crop-management", "material-handling"],
  },
  {
    id: "livestock-handling",
    name: "Livestock handling",
    category: "physical",
    description: "Low-stress handling, feeding, and daily animal care.",
    industries: ["agriculture"],
    relatedSkills: ["animal-health", "manual-labor"],
  },
  {
    id: "animal-health",
    name: "Animal health",
    category: "environmental",
    description: "Spotting illness early and following herd health protocols.",
    industries: ["agriculture"],
    relatedSkills: ["livestock-handling"],
  },
  {
    id: "greenhouse-ops",
    name: "Greenhouse operations",
    category: "technical",
    description: "Running climate, light, and nutrient systems under cover.",
    industries: ["agriculture"],
    relatedSkills: ["hydroponics", "horticulture", "sensors-iot"],
  },
  {
    id: "hydroponics",
    name: "Hydroponics & CEA",
    category: "technical",
    description: "Soil-free growing: nutrient film, DWC, and vertical systems.",
    industries: ["agriculture"],
    relatedSkills: ["greenhouse-ops", "water-management"],
  },

  // --- Digital & data -----------------------------------------------------
  {
    id: "cad-software",
    name: "CAD & design software",
    category: "digital",
    description: "Drafting layouts and plans that others can build from.",
    industries: ["solar", "landscaping", "renovation"],
    relatedSkills: ["blueprint-reading", "system-design"],
  },
  {
    id: "drone-operation",
    name: "Drone operation",
    category: "digital",
    description: "Flying survey missions and capturing usable imagery.",
    industries: ["agriculture", "solar", "landscaping"],
    relatedSkills: ["data-analysis", "gps-gis"],
  },
  {
    id: "gps-gis",
    name: "GPS & GIS mapping",
    category: "digital",
    description: "Field mapping, guidance systems, and spatial data.",
    industries: ["agriculture", "landscaping", "solar"],
    relatedSkills: ["drone-operation", "data-analysis"],
  },
  {
    id: "sensors-iot",
    name: "Sensors & monitoring",
    category: "digital",
    description: "Installing and reading field sensors and telemetry.",
    industries: ["agriculture", "solar", "landscaping"],
    relatedSkills: ["data-analysis", "irrigation-controls"],
  },
  {
    id: "data-analysis",
    name: "Data analysis",
    category: "digital",
    description: "Turning readings and yields into decisions.",
    industries: ["solar", "agriculture", "renovation"],
    relatedSkills: ["sensors-iot", "software-tools"],
  },
  {
    id: "software-tools",
    name: "Software & apps",
    category: "digital",
    description: "Comfort with scheduling, estimating, and monitoring platforms.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["data-analysis", "project-management"],
  },
  {
    id: "automation-robotics",
    name: "Automation & robotics",
    category: "digital",
    description: "Setting up and supervising autonomous machines.",
    industries: ["agriculture", "solar"],
    relatedSkills: ["sensors-iot", "troubleshooting", "gps-gis"],
  },

  // --- Safety & compliance ------------------------------------------------
  {
    id: "safety-osha",
    name: "Jobsite safety",
    category: "safety",
    description: "Hazard awareness, PPE, and stopping unsafe work.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["ladder-roof", "code-knowledge"],
  },
  {
    id: "code-knowledge",
    name: "Codes & permitting",
    category: "safety",
    description: "Knowing which rules apply and how to get work approved.",
    industries: ["solar", "renovation", "landscaping"],
    relatedSkills: ["safety-osha", "inspection"],
  },
  {
    id: "inspection",
    name: "Inspection & QA",
    category: "safety",
    description: "Verifying work against spec and catching defects early.",
    industries: ["solar", "renovation"],
    relatedSkills: ["code-knowledge", "attention-detail"],
  },
  {
    id: "attention-detail",
    name: "Attention to detail",
    category: "people",
    description: "Noticing the small things that decide whether work holds up.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["inspection", "finish-work"],
  },

  // --- Business & people --------------------------------------------------
  {
    id: "customer-service",
    name: "Customer service",
    category: "people",
    description: "Setting expectations and keeping clients informed.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["sales", "communication"],
  },
  {
    id: "communication",
    name: "Clear communication",
    category: "people",
    description: "Explaining technical work to non-technical people.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["customer-service", "crew-leadership"],
  },
  {
    id: "sales",
    name: "Sales & consultation",
    category: "business",
    description: "Qualifying a lead and proposing the right scope honestly.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["customer-service", "estimating"],
  },
  {
    id: "estimating",
    name: "Estimating & bidding",
    category: "business",
    description: "Pricing labor and materials so the job is actually profitable.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["math-fundamentals", "sales", "project-management"],
  },
  {
    id: "project-management",
    name: "Project management",
    category: "business",
    description: "Sequencing trades, materials, and deadlines.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["scheduling", "crew-leadership", "estimating"],
  },
  {
    id: "scheduling",
    name: "Scheduling & logistics",
    category: "business",
    description: "Getting the right people and materials on site on the right day.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["project-management", "inventory"],
  },
  {
    id: "crew-leadership",
    name: "Crew leadership",
    category: "people",
    description: "Directing a crew, training juniors, and holding a standard.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["communication", "training-others"],
  },
  {
    id: "training-others",
    name: "Training others",
    category: "people",
    description: "Bringing new people up to competence safely.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["crew-leadership", "communication"],
  },
  {
    id: "business-management",
    name: "Business management",
    category: "business",
    description: "Cash flow, insurance, licensing, and keeping the doors open.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["estimating", "marketing", "project-management"],
  },
  {
    id: "marketing",
    name: "Marketing & lead generation",
    category: "business",
    description: "Getting a steady pipeline of the work you actually want.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["sales", "business-management"],
  },
  {
    id: "inventory",
    name: "Inventory & procurement",
    category: "business",
    description: "Sourcing and tracking materials without tying up cash.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["scheduling", "material-handling"],
  },
  {
    id: "math-fundamentals",
    name: "Practical math",
    category: "technical",
    description: "Areas, volumes, slopes, and load calculations you can trust.",
    industries: ["solar", "landscaping", "renovation", "agriculture"],
    relatedSkills: ["measuring", "estimating"],
  },
  {
    id: "record-keeping",
    name: "Record keeping & compliance",
    category: "business",
    description: "Documentation that satisfies auditors, buyers, and inspectors.",
    industries: ["agriculture", "renovation", "solar"],
    relatedSkills: ["code-knowledge", "business-management"],
  },
]

export const SKILL_BY_ID: Record<string, Skill> = Object.fromEntries(
  SKILLS.map((skill) => [skill.id, skill]),
)

export function getSkill(id: string): Skill | undefined {
  return SKILL_BY_ID[id]
}

export function skillName(id: string): string {
  return SKILL_BY_ID[id]?.name ?? id
}
